server.port=8080
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT
app.jwt.secret=UJR9ZbPf2AzxKPVqLWl9UMENqZaJNg/RI0CiTaSDS4A=

app.jwt.expiration-ms=1800000

# CORS allowed origins (comma separated)
app.cors.allowed-origins=http://localhost:3000,http://localhost:4200





